name: Scrape Matches to JSON

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run scraper
        env:
          SURL1: ${{ secrets.SURL1 }}
          SURL2: ${{ secrets.SURL2 }}
          SURL3: ${{ secrets.SURL3 }}
          SURL4: ${{ secrets.SURL4 }}
          SURL5: ${{ secrets.SURL5 }}
        run: python scraper.py

      - name: Commit JSON
        run: |
          git config --global user.name "github-bot"
          git config --global user.email "bot@github.com"
          git add matches.json
          git commit -m "Auto update matches JSON" || echo "No changes"
          git pull --rebase origin main
          git push origin main
          
